SELECT TOP (1) [Name]
      ,[Cost]
      ,[Dmg_S]
      ,[Dmg_M]
      ,[Critical]
      ,[Range]
      ,[Weight]
      ,[Type]
      ,[Special]
      ,[Property]
      ,[Proficiency]
      ,[Description]
      ,[Currency]
      ,[Id]
  FROM [PFDB_NEW].[dbo].[Items_Weapon]
  ORDER BY NEWID()
