SELECT TOP (1) [Name]
      ,[Cost]
      ,[Armor_Shield_Bonus]
      ,[Max_Dex_Bonus]
      ,[Armor_Check_Penalty]
      ,[Arcane_Spell_Failure_Chance]
      ,[Speed30]
      ,[Speed20]
      ,[Weight]
      ,[Proficiency]
      ,[Description]
      ,[Currency]
      ,[Id]
  FROM [PFDB_NEW].[dbo].[Items_Armor]
  ORDER BY NEWID()
